language: python
cache: pip
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial    # required for Python >= 3.7 (travis-ci/travis-ci#9069)
install:
  # install dependencies from setup.py (there are none for remi)
  - pip install -e .
  # install optional packages (for linting, coverage, browser control)
  - pip install flake8
  - pip install coverage
  # - pip install selenium
  # install dependencies for specific examples
  - pip install matplotlib
  - pip install Pillow
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  # command to run tests
  # - python -m unittest discover -t . -s test/ -v
  # - python test/
  - coverage run test/
  - coverage report --include="examples/*,test/*"
  - coverage report --include="remi/*,editor/*"
# addons:
#   sauce_connect: true
